services:
  impensa-server-dotnet-postgres:
    container_name: impensa-server-dotnet-postgres
    image: docker.io/postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: impensa-dotnet
