name: Build and Analyze
on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Restore tools
      run: dotnet tool restore
      
    - name: Begin SonarCloud analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin \
          /o:"impensa-sonar" \
          /k:"neiios_impensa-server-dotnet" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.cs.opencover.reportsPaths="ImpensaTest/coverage.opencover.xml" \
          /d:sonar.coverage.exclusions="**/Migrations/**" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.scanner.scanAll=false
        
    - name: Build
      run: dotnet build
      
    - name: Test with coverage
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      
    - name: Debug coverage file location
      run: ls -lah ImpensaTest
        
    - name: End SonarCloud analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
